/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_common_tool_crypto_kdf_NativeBlake3Kdf */

#ifndef _Included_edu_alibaba_mpc4j_common_tool_crypto_kdf_NativeBlake3Kdf
#define _Included_edu_alibaba_mpc4j_common_tool_crypto_kdf_NativeBlake3Kdf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_common_tool_crypto_kdf_NativeBlake3Kdf
 * Method:    nativeDeriveKey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_crypto_kdf_NativeBlake3Kdf_nativeDeriveKey
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
