/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_common_tool_crypto_hash_NativeSha256Hash */

#ifndef _Included_edu_alibaba_mpc4j_common_tool_crypto_hash_NativeSha256Hash
#define _Included_edu_alibaba_mpc4j_common_tool_crypto_hash_NativeSha256Hash
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_alibaba_mpc4j_common_tool_crypto_hash_NativeSha256Hash_UNIT_BYTE_LENGTH
#define edu_alibaba_mpc4j_common_tool_crypto_hash_NativeSha256Hash_UNIT_BYTE_LENGTH 32L
/*
 * Class:     edu_alibaba_mpc4j_common_tool_crypto_hash_NativeSha256Hash
 * Method:    digest
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_crypto_hash_NativeSha256Hash_digest
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
