/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64 */

#ifndef _Included_edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64
#define _Included_edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64_L
#define edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64_L 64L
#undef edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64_BYTE_L
#define edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64_BYTE_L 8L
/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64
 * Method:    nativeMul
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64_nativeMul
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64
 * Method:    nativeMuli
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64_nativeMuli
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64
 * Method:    nativeInv
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64_nativeInv
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64
 * Method:    nativeInvi
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64_nativeInvi
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64
 * Method:    nativeDiv
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64_nativeDiv
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64
 * Method:    nativeDivi
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_gf64_NtlGf64_nativeDivi
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
