/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_work_femur_FemurSealPirNativeUtils */

#ifndef _Included_edu_alibaba_work_femur_FemurSealPirNativeUtils
#define _Included_edu_alibaba_work_femur_FemurSealPirNativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_work_femur_FemurSealPirNativeUtils
 * Method:    generateEncryptionParams
 * Signature: (IJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_work_femur_FemurSealPirNativeUtils_generateEncryptionParams
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     edu_alibaba_work_femur_FemurSealPirNativeUtils
 * Method:    keyGen
 * Signature: ([B)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_work_femur_FemurSealPirNativeUtils_keyGen
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_alibaba_work_femur_FemurSealPirNativeUtils
 * Method:    transformToNtt
 * Signature: ([BLjava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_work_femur_FemurSealPirNativeUtils_transformToNtt
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     edu_alibaba_work_femur_FemurSealPirNativeUtils
 * Method:    transformFromNtt
 * Signature: ([B[[B)[[J
 */
JNIEXPORT jobjectArray JNICALL Java_edu_alibaba_work_femur_FemurSealPirNativeUtils_transformFromNtt
  (JNIEnv *, jclass, jbyteArray, jobjectArray);

/*
 * Class:     edu_alibaba_work_femur_FemurSealPirNativeUtils
 * Method:    generateQuery
 * Signature: ([B[B[B[I[I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_work_femur_FemurSealPirNativeUtils_generateQuery
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jintArray, jintArray);

/*
 * Class:     edu_alibaba_work_femur_FemurSealPirNativeUtils
 * Method:    generateReply
 * Signature: ([B[BLjava/util/List;[[B[I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_work_femur_FemurSealPirNativeUtils_generateReply
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject, jobjectArray, jintArray);

/*
 * Class:     edu_alibaba_work_femur_FemurSealPirNativeUtils
 * Method:    decryptReply
 * Signature: ([B[BLjava/util/List;I)[J
 */
JNIEXPORT jlongArray JNICALL Java_edu_alibaba_work_femur_FemurSealPirNativeUtils_decryptReply
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject, jint);

/*
 * Class:     edu_alibaba_work_femur_FemurSealPirNativeUtils
 * Method:    expansionRatio
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_edu_alibaba_work_femur_FemurSealPirNativeUtils_expansionRatio
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
