/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_common_tool_galoisfield_sgf2k_NtlSubSgf2k */

#ifndef _Included_edu_alibaba_mpc4j_common_tool_galoisfield_sgf2k_NtlSubSgf2k
#define _Included_edu_alibaba_mpc4j_common_tool_galoisfield_sgf2k_NtlSubSgf2k
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_sgf2k_NtlSubSgf2k
 * Method:    nativeInit
 * Signature: (I[B[[B)V
 */
JNIEXPORT void JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_sgf2k_NtlSubSgf2k_nativeInit
  (JNIEnv *, jobject, jint, jbyteArray, jobjectArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_sgf2k_NtlSubSgf2k
 * Method:    nativeFieldMul
 * Signature: (I[[B[[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_sgf2k_NtlSubSgf2k_nativeFieldMul
  (JNIEnv *, jobject, jint, jobjectArray, jobjectArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_sgf2k_NtlSubSgf2k
 * Method:    nativeFieldInv
 * Signature: (I[[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_sgf2k_NtlSubSgf2k_nativeFieldInv
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_sgf2k_NtlSubSgf2k
 * Method:    nativeFieldDiv
 * Signature: (I[[B[[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_sgf2k_NtlSubSgf2k_nativeFieldDiv
  (JNIEnv *, jobject, jint, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
