/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils */

#ifndef _Included_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils
#define _Included_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils
 * Method:    generateEncryptionParams
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils_generateEncryptionParams
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils
 * Method:    keyGen
 * Signature: ([B)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils_keyGen
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils
 * Method:    preprocessDatabase
 * Signature: ([BLjava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils_preprocessDatabase
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils
 * Method:    encryptSecretKey
 * Signature: ([B[B[B)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils_encryptSecretKey
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils
 * Method:    generateQuery
 * Signature: ([B[B[B[I[I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils_generateQuery
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jintArray, jintArray);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils
 * Method:    generateReply
 * Signature: ([B[B[BLjava/util/List;Ljava/util/List;Ljava/util/List;[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils_generateReply
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jobject, jobject, jobject, jintArray);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils
 * Method:    decryptReply
 * Signature: ([B[B[B)[J
 */
JNIEXPORT jlongArray JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_onion_OnionStdIdxPirNativeUtils_decryptReply
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
