/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_s2pc_pir_stdpir_index_vectorized_VectorizedStdIdxPirNativeUtils */

#ifndef _Included_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_vectorized_VectorizedStdIdxPirNativeUtils
#define _Included_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_vectorized_VectorizedStdIdxPirNativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_vectorized_VectorizedStdIdxPirNativeUtils
 * Method:    generateEncryptionParams
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_vectorized_VectorizedStdIdxPirNativeUtils_generateEncryptionParams
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_vectorized_VectorizedStdIdxPirNativeUtils
 * Method:    keyGen
 * Signature: ([B)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_vectorized_VectorizedStdIdxPirNativeUtils_keyGen
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_vectorized_VectorizedStdIdxPirNativeUtils
 * Method:    preprocessDatabase
 * Signature: ([B[[J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_vectorized_VectorizedStdIdxPirNativeUtils_preprocessDatabase
  (JNIEnv *, jclass, jbyteArray, jobjectArray);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_vectorized_VectorizedStdIdxPirNativeUtils
 * Method:    generateQuery
 * Signature: ([B[B[B[[J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_vectorized_VectorizedStdIdxPirNativeUtils_generateQuery
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jobjectArray);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_vectorized_VectorizedStdIdxPirNativeUtils
 * Method:    generateReply
 * Signature: ([BLjava/util/List;Ljava/util/List;[B[B[BIII)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_vectorized_VectorizedStdIdxPirNativeUtils_generateReply
  (JNIEnv *, jclass, jbyteArray, jobject, jobject, jbyteArray, jbyteArray, jbyteArray, jint, jint, jint);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_vectorized_VectorizedStdIdxPirNativeUtils
 * Method:    decryptReply
 * Signature: ([B[B[B)[J
 */
JNIEXPORT jlongArray JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_vectorized_VectorizedStdIdxPirNativeUtils_decryptReply
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
