/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils */

#ifndef _Included_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils
#define _Included_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils
 * Method:    generateEncryptionParams
 * Signature: (IJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils_generateEncryptionParams
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils
 * Method:    keyGen
 * Signature: ([B)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils_keyGen
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils
 * Method:    nttTransform
 * Signature: ([BLjava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils_nttTransform
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils
 * Method:    generateQuery
 * Signature: ([B[B[B[I[I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils_generateQuery
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jintArray, jintArray);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils
 * Method:    generateReply
 * Signature: ([BLjava/util/List;[[B[I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils_generateReply
  (JNIEnv *, jclass, jbyteArray, jobject, jobjectArray, jintArray);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils
 * Method:    decryptReply
 * Signature: ([B[BLjava/util/List;I)[J
 */
JNIEXPORT jlongArray JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils_decryptReply
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject, jint);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils
 * Method:    expansionRatio
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_edu_alibaba_mpc4j_s2pc_pir_stdpir_index_xpir_XpirStdIdxPirNativeUtils_expansionRatio
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
