/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_common_tool_galoisfield_gf2k_NtlGf2k */

#ifndef _Included_edu_alibaba_mpc4j_common_tool_galoisfield_gf2k_NtlGf2k
#define _Included_edu_alibaba_mpc4j_common_tool_galoisfield_gf2k_NtlGf2k
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_gf2k_NtlGf2k
 * Method:    nativeMul
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_gf2k_NtlGf2k_nativeMul
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_gf2k_NtlGf2k
 * Method:    nativeMuli
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_gf2k_NtlGf2k_nativeMuli
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
