/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_common_tool_network_waksman_NativeWaksmanNetwork */

#ifndef _Included_edu_alibaba_mpc4j_common_tool_network_waksman_NativeWaksmanNetwork
#define _Included_edu_alibaba_mpc4j_common_tool_network_waksman_NativeWaksmanNetwork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_common_tool_network_waksman_NativeWaksmanNetwork
 * Method:    generateBenesNetwork
 * Signature: ([I)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_edu_alibaba_mpc4j_common_tool_network_waksman_NativeWaksmanNetwork_generateBenesNetwork
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
