/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_common_tool_network_benes_NativeBenesNetwork */

#ifndef _Included_edu_alibaba_mpc4j_common_tool_network_benes_NativeBenesNetwork
#define _Included_edu_alibaba_mpc4j_common_tool_network_benes_NativeBenesNetwork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_common_tool_network_benes_NativeBenesNetwork
 * Method:    generateBenesNetwork
 * Signature: ([I)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_edu_alibaba_mpc4j_common_tool_network_benes_NativeBenesNetwork_generateBenesNetwork
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
