/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils */

#ifndef _Included_edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils
#define _Included_edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils
 * Method:    genEncryptionParameters
 * Signature: (IJ[I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils_genEncryptionParameters
  (JNIEnv *, jclass, jint, jlong, jintArray);

/*
 * Class:     edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils
 * Method:    processDatabase
 * Signature: ([B[[JI)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils_processDatabase
  (JNIEnv *, jclass, jbyteArray, jobjectArray, jint);

/*
 * Class:     edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils
 * Method:    computeEncryptedPowers
 * Signature: ([B[BLjava/util/List;[[I[II)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils_computeEncryptedPowers
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject, jobjectArray, jintArray, jint);

/*
 * Class:     edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils
 * Method:    optComputeMatches
 * Signature: ([B[BLjava/util/List;Ljava/util/List;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils_optComputeMatches
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject, jobject, jint);

/*
 * Class:     edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils
 * Method:    naiveComputeMatches
 * Signature: ([BLjava/util/List;Ljava/util/List;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils_naiveComputeMatches
  (JNIEnv *, jclass, jbyteArray, jobject, jobject);

/*
 * Class:     edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils
 * Method:    generateQuery
 * Signature: ([B[B[B[[J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils_generateQuery
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jobjectArray);

/*
 * Class:     edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils
 * Method:    decodeReply
 * Signature: ([B[B[B)[J
 */
JNIEXPORT jlongArray JNICALL Java_edu_alibaba_mpc4j_work_psipir_Lpzl24BatchPirNativeUtils_decodeReply
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
