/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_common_tool_galoisfield_gf2e_NtlNativeGf2e */

#ifndef _Included_edu_alibaba_mpc4j_common_tool_galoisfield_gf2e_NtlNativeGf2e
#define _Included_edu_alibaba_mpc4j_common_tool_galoisfield_gf2e_NtlNativeGf2e
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_gf2e_NtlNativeGf2e
 * Method:    nativeMul
 * Signature: ([BI[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_gf2e_NtlNativeGf2e_nativeMul
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_gf2e_NtlNativeGf2e
 * Method:    nativeMuli
 * Signature: ([BI[B[B)V
 */
JNIEXPORT void JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_gf2e_NtlNativeGf2e_nativeMuli
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_gf2e_NtlNativeGf2e
 * Method:    nativeDiv
 * Signature: ([BI[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_gf2e_NtlNativeGf2e_nativeDiv
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_gf2e_NtlNativeGf2e
 * Method:    nativeDivi
 * Signature: ([BI[B[B)V
 */
JNIEXPORT void JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_gf2e_NtlNativeGf2e_nativeDivi
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_gf2e_NtlNativeGf2e
 * Method:    nativeInv
 * Signature: ([BI[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_gf2e_NtlNativeGf2e_nativeInv
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_galoisfield_gf2e_NtlNativeGf2e
 * Method:    nativeInvi
 * Signature: ([BI[B)V
 */
JNIEXPORT void JNICALL Java_edu_alibaba_mpc4j_common_tool_galoisfield_gf2e_NtlNativeGf2e_nativeInvi
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
