// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NettyRpc.proto

package edu.alibaba.mpc4j.common.rpc.impl.netty.protobuf;

public final class NettyRpcProtobuf {
  private NettyRpcProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataPacketProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataPacketProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 协议由两部分组成：head、payload，分别由HeaderProto和PayloadProto定义。
     * </pre>
     *
     * <code>.DataPacketProto.HeaderProto headerProto = 1;</code>
     * @return Whether the headerProto field is set.
     */
    boolean hasHeaderProto();
    /**
     * <pre>
     * 协议由两部分组成：head、payload，分别由HeaderProto和PayloadProto定义。
     * </pre>
     *
     * <code>.DataPacketProto.HeaderProto headerProto = 1;</code>
     * @return The headerProto.
     */
    DataPacketProto.HeaderProto getHeaderProto();
    /**
     * <pre>
     * 协议由两部分组成：head、payload，分别由HeaderProto和PayloadProto定义。
     * </pre>
     *
     * <code>.DataPacketProto.HeaderProto headerProto = 1;</code>
     */
    DataPacketProto.HeaderProtoOrBuilder getHeaderProtoOrBuilder();

    /**
     * <code>.DataPacketProto.PayloadProto payloadProto = 2;</code>
     * @return Whether the payloadProto field is set.
     */
    boolean hasPayloadProto();
    /**
     * <code>.DataPacketProto.PayloadProto payloadProto = 2;</code>
     * @return The payloadProto.
     */
    DataPacketProto.PayloadProto getPayloadProto();
    /**
     * <code>.DataPacketProto.PayloadProto payloadProto = 2;</code>
     */
    DataPacketProto.PayloadProtoOrBuilder getPayloadProtoOrBuilder();
  }
  /**
   * Protobuf type {@code DataPacketProto}
   */
  public static final class DataPacketProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataPacketProto)
      DataPacketProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataPacketProto.newBuilder() to construct.
    private DataPacketProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataPacketProto() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataPacketProto();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataPacketProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              HeaderProto.Builder subBuilder = null;
              if (headerProto_ != null) {
                subBuilder = headerProto_.toBuilder();
              }
              headerProto_ = input.readMessage(HeaderProto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(headerProto_);
                headerProto_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              PayloadProto.Builder subBuilder = null;
              if (payloadProto_ != null) {
                subBuilder = payloadProto_.toBuilder();
              }
              payloadProto_ = input.readMessage(PayloadProto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(payloadProto_);
                payloadProto_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NettyRpcProtobuf.internal_static_DataPacketProto_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NettyRpcProtobuf.internal_static_DataPacketProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DataPacketProto.class, Builder.class);
    }

    public interface HeaderProtoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:DataPacketProto.HeaderProto)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * 任务ID
       * </pre>
       *
       * <code>int64 taskId = 1;</code>
       * @return The taskId.
       */
      long getTaskId();

      /**
       * <pre>
       * 协议ID
       * </pre>
       *
       * <code>int32 ptoId = 2;</code>
       * @return The ptoId.
       */
      int getPtoId();

      /**
       * <pre>
       * 步骤ID
       * </pre>
       *
       * <code>int32 stepId = 3;</code>
       * @return The stepId.
       */
      int getStepId();

      /**
       * <pre>
       * 补充信息
       * </pre>
       *
       * <code>int64 extraInfo = 4;</code>
       * @return The extraInfo.
       */
      long getExtraInfo();

      /**
       * <pre>
       * 发送方ID
       * </pre>
       *
       * <code>int32 senderId = 5;</code>
       * @return The senderId.
       */
      int getSenderId();

      /**
       * <pre>
       * 接收方ID
       * </pre>
       *
       * <code>int32 receiverId = 6;</code>
       * @return The receiverId.
       */
      int getReceiverId();
    }
    /**
     * <pre>
     * 定义head
     * </pre>
     *
     * Protobuf type {@code DataPacketProto.HeaderProto}
     */
    public static final class HeaderProto extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:DataPacketProto.HeaderProto)
        HeaderProtoOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use HeaderProto.newBuilder() to construct.
      private HeaderProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private HeaderProto() {
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new HeaderProto();
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private HeaderProto(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                taskId_ = input.readInt64();
                break;
              }
              case 16: {

                ptoId_ = input.readInt32();
                break;
              }
              case 24: {

                stepId_ = input.readInt32();
                break;
              }
              case 32: {

                extraInfo_ = input.readInt64();
                break;
              }
              case 40: {

                senderId_ = input.readInt32();
                break;
              }
              case 48: {

                receiverId_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NettyRpcProtobuf.internal_static_DataPacketProto_HeaderProto_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NettyRpcProtobuf.internal_static_DataPacketProto_HeaderProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeaderProto.class, Builder.class);
      }

      public static final int TASKID_FIELD_NUMBER = 1;
      private long taskId_;
      /**
       * <pre>
       * 任务ID
       * </pre>
       *
       * <code>int64 taskId = 1;</code>
       * @return The taskId.
       */
      @Override
      public long getTaskId() {
        return taskId_;
      }

      public static final int PTOID_FIELD_NUMBER = 2;
      private int ptoId_;
      /**
       * <pre>
       * 协议ID
       * </pre>
       *
       * <code>int32 ptoId = 2;</code>
       * @return The ptoId.
       */
      @Override
      public int getPtoId() {
        return ptoId_;
      }

      public static final int STEPID_FIELD_NUMBER = 3;
      private int stepId_;
      /**
       * <pre>
       * 步骤ID
       * </pre>
       *
       * <code>int32 stepId = 3;</code>
       * @return The stepId.
       */
      @Override
      public int getStepId() {
        return stepId_;
      }

      public static final int EXTRAINFO_FIELD_NUMBER = 4;
      private long extraInfo_;
      /**
       * <pre>
       * 补充信息
       * </pre>
       *
       * <code>int64 extraInfo = 4;</code>
       * @return The extraInfo.
       */
      @Override
      public long getExtraInfo() {
        return extraInfo_;
      }

      public static final int SENDERID_FIELD_NUMBER = 5;
      private int senderId_;
      /**
       * <pre>
       * 发送方ID
       * </pre>
       *
       * <code>int32 senderId = 5;</code>
       * @return The senderId.
       */
      @Override
      public int getSenderId() {
        return senderId_;
      }

      public static final int RECEIVERID_FIELD_NUMBER = 6;
      private int receiverId_;
      /**
       * <pre>
       * 接收方ID
       * </pre>
       *
       * <code>int32 receiverId = 6;</code>
       * @return The receiverId.
       */
      @Override
      public int getReceiverId() {
        return receiverId_;
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (taskId_ != 0L) {
          output.writeInt64(1, taskId_);
        }
        if (ptoId_ != 0) {
          output.writeInt32(2, ptoId_);
        }
        if (stepId_ != 0) {
          output.writeInt32(3, stepId_);
        }
        if (extraInfo_ != 0L) {
          output.writeInt64(4, extraInfo_);
        }
        if (senderId_ != 0) {
          output.writeInt32(5, senderId_);
        }
        if (receiverId_ != 0) {
          output.writeInt32(6, receiverId_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (taskId_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, taskId_);
        }
        if (ptoId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, ptoId_);
        }
        if (stepId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, stepId_);
        }
        if (extraInfo_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(4, extraInfo_);
        }
        if (senderId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, senderId_);
        }
        if (receiverId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(6, receiverId_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof HeaderProto)) {
          return super.equals(obj);
        }
        HeaderProto other = (HeaderProto) obj;

        if (getTaskId()
            != other.getTaskId()) return false;
        if (getPtoId()
            != other.getPtoId()) return false;
        if (getStepId()
            != other.getStepId()) return false;
        if (getExtraInfo()
            != other.getExtraInfo()) return false;
        if (getSenderId()
            != other.getSenderId()) return false;
        if (getReceiverId()
            != other.getReceiverId()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TASKID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTaskId());
        hash = (37 * hash) + PTOID_FIELD_NUMBER;
        hash = (53 * hash) + getPtoId();
        hash = (37 * hash) + STEPID_FIELD_NUMBER;
        hash = (53 * hash) + getStepId();
        hash = (37 * hash) + EXTRAINFO_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getExtraInfo());
        hash = (37 * hash) + SENDERID_FIELD_NUMBER;
        hash = (53 * hash) + getSenderId();
        hash = (37 * hash) + RECEIVERID_FIELD_NUMBER;
        hash = (53 * hash) + getReceiverId();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static HeaderProto parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static HeaderProto parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static HeaderProto parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static HeaderProto parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static HeaderProto parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static HeaderProto parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static HeaderProto parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static HeaderProto parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static HeaderProto parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static HeaderProto parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static HeaderProto parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static HeaderProto parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(HeaderProto prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * 定义head
       * </pre>
       *
       * Protobuf type {@code DataPacketProto.HeaderProto}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:DataPacketProto.HeaderProto)
          HeaderProtoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return NettyRpcProtobuf.internal_static_DataPacketProto_HeaderProto_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return NettyRpcProtobuf.internal_static_DataPacketProto_HeaderProto_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  HeaderProto.class, Builder.class);
        }

        // Construct using edu.alibaba.mpc4j.common.rpc.impl.netty.protobuf.NettyRpcProtobuf.DataPacketProto.HeaderProto.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          taskId_ = 0L;

          ptoId_ = 0;

          stepId_ = 0;

          extraInfo_ = 0L;

          senderId_ = 0;

          receiverId_ = 0;

          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return NettyRpcProtobuf.internal_static_DataPacketProto_HeaderProto_descriptor;
        }

        @Override
        public HeaderProto getDefaultInstanceForType() {
          return HeaderProto.getDefaultInstance();
        }

        @Override
        public HeaderProto build() {
          HeaderProto result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public HeaderProto buildPartial() {
          HeaderProto result = new HeaderProto(this);
          result.taskId_ = taskId_;
          result.ptoId_ = ptoId_;
          result.stepId_ = stepId_;
          result.extraInfo_ = extraInfo_;
          result.senderId_ = senderId_;
          result.receiverId_ = receiverId_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof HeaderProto) {
            return mergeFrom((HeaderProto)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(HeaderProto other) {
          if (other == HeaderProto.getDefaultInstance()) return this;
          if (other.getTaskId() != 0L) {
            setTaskId(other.getTaskId());
          }
          if (other.getPtoId() != 0) {
            setPtoId(other.getPtoId());
          }
          if (other.getStepId() != 0) {
            setStepId(other.getStepId());
          }
          if (other.getExtraInfo() != 0L) {
            setExtraInfo(other.getExtraInfo());
          }
          if (other.getSenderId() != 0) {
            setSenderId(other.getSenderId());
          }
          if (other.getReceiverId() != 0) {
            setReceiverId(other.getReceiverId());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          HeaderProto parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (HeaderProto) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long taskId_ ;
        /**
         * <pre>
         * 任务ID
         * </pre>
         *
         * <code>int64 taskId = 1;</code>
         * @return The taskId.
         */
        @Override
        public long getTaskId() {
          return taskId_;
        }
        /**
         * <pre>
         * 任务ID
         * </pre>
         *
         * <code>int64 taskId = 1;</code>
         * @param value The taskId to set.
         * @return This builder for chaining.
         */
        public Builder setTaskId(long value) {
          
          taskId_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 任务ID
         * </pre>
         *
         * <code>int64 taskId = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearTaskId() {
          
          taskId_ = 0L;
          onChanged();
          return this;
        }

        private int ptoId_ ;
        /**
         * <pre>
         * 协议ID
         * </pre>
         *
         * <code>int32 ptoId = 2;</code>
         * @return The ptoId.
         */
        @Override
        public int getPtoId() {
          return ptoId_;
        }
        /**
         * <pre>
         * 协议ID
         * </pre>
         *
         * <code>int32 ptoId = 2;</code>
         * @param value The ptoId to set.
         * @return This builder for chaining.
         */
        public Builder setPtoId(int value) {
          
          ptoId_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 协议ID
         * </pre>
         *
         * <code>int32 ptoId = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearPtoId() {
          
          ptoId_ = 0;
          onChanged();
          return this;
        }

        private int stepId_ ;
        /**
         * <pre>
         * 步骤ID
         * </pre>
         *
         * <code>int32 stepId = 3;</code>
         * @return The stepId.
         */
        @Override
        public int getStepId() {
          return stepId_;
        }
        /**
         * <pre>
         * 步骤ID
         * </pre>
         *
         * <code>int32 stepId = 3;</code>
         * @param value The stepId to set.
         * @return This builder for chaining.
         */
        public Builder setStepId(int value) {
          
          stepId_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 步骤ID
         * </pre>
         *
         * <code>int32 stepId = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearStepId() {
          
          stepId_ = 0;
          onChanged();
          return this;
        }

        private long extraInfo_ ;
        /**
         * <pre>
         * 补充信息
         * </pre>
         *
         * <code>int64 extraInfo = 4;</code>
         * @return The extraInfo.
         */
        @Override
        public long getExtraInfo() {
          return extraInfo_;
        }
        /**
         * <pre>
         * 补充信息
         * </pre>
         *
         * <code>int64 extraInfo = 4;</code>
         * @param value The extraInfo to set.
         * @return This builder for chaining.
         */
        public Builder setExtraInfo(long value) {
          
          extraInfo_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 补充信息
         * </pre>
         *
         * <code>int64 extraInfo = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearExtraInfo() {
          
          extraInfo_ = 0L;
          onChanged();
          return this;
        }

        private int senderId_ ;
        /**
         * <pre>
         * 发送方ID
         * </pre>
         *
         * <code>int32 senderId = 5;</code>
         * @return The senderId.
         */
        @Override
        public int getSenderId() {
          return senderId_;
        }
        /**
         * <pre>
         * 发送方ID
         * </pre>
         *
         * <code>int32 senderId = 5;</code>
         * @param value The senderId to set.
         * @return This builder for chaining.
         */
        public Builder setSenderId(int value) {
          
          senderId_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 发送方ID
         * </pre>
         *
         * <code>int32 senderId = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearSenderId() {
          
          senderId_ = 0;
          onChanged();
          return this;
        }

        private int receiverId_ ;
        /**
         * <pre>
         * 接收方ID
         * </pre>
         *
         * <code>int32 receiverId = 6;</code>
         * @return The receiverId.
         */
        @Override
        public int getReceiverId() {
          return receiverId_;
        }
        /**
         * <pre>
         * 接收方ID
         * </pre>
         *
         * <code>int32 receiverId = 6;</code>
         * @param value The receiverId to set.
         * @return This builder for chaining.
         */
        public Builder setReceiverId(int value) {
          
          receiverId_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 接收方ID
         * </pre>
         *
         * <code>int32 receiverId = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearReceiverId() {
          
          receiverId_ = 0;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:DataPacketProto.HeaderProto)
      }

      // @@protoc_insertion_point(class_scope:DataPacketProto.HeaderProto)
      private static final HeaderProto DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new HeaderProto();
      }

      public static HeaderProto getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<HeaderProto>
          PARSER = new com.google.protobuf.AbstractParser<HeaderProto>() {
        @Override
        public HeaderProto parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new HeaderProto(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<HeaderProto> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<HeaderProto> getParserForType() {
        return PARSER;
      }

      @Override
      public HeaderProto getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface PayloadProtoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:DataPacketProto.PayloadProto)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * repeated表示可以存在多个（类似数组）
       * </pre>
       *
       * <code>repeated bytes payloadBytes = 1;</code>
       * @return A list containing the payloadBytes.
       */
      java.util.List<com.google.protobuf.ByteString> getPayloadBytesList();
      /**
       * <pre>
       * repeated表示可以存在多个（类似数组）
       * </pre>
       *
       * <code>repeated bytes payloadBytes = 1;</code>
       * @return The count of payloadBytes.
       */
      int getPayloadBytesCount();
      /**
       * <pre>
       * repeated表示可以存在多个（类似数组）
       * </pre>
       *
       * <code>repeated bytes payloadBytes = 1;</code>
       * @param index The index of the element to return.
       * @return The payloadBytes at the given index.
       */
      com.google.protobuf.ByteString getPayloadBytes(int index);
    }
    /**
     * <pre>
     * 定义payload
     * </pre>
     *
     * Protobuf type {@code DataPacketProto.PayloadProto}
     */
    public static final class PayloadProto extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:DataPacketProto.PayloadProto)
        PayloadProtoOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use PayloadProto.newBuilder() to construct.
      private PayloadProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PayloadProto() {
        payloadBytes_ = java.util.Collections.emptyList();
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new PayloadProto();
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private PayloadProto(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  payloadBytes_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                  mutable_bitField0_ |= 0x00000001;
                }
                payloadBytes_.add(input.readBytes());
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) != 0)) {
            payloadBytes_ = java.util.Collections.unmodifiableList(payloadBytes_); // C
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NettyRpcProtobuf.internal_static_DataPacketProto_PayloadProto_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NettyRpcProtobuf.internal_static_DataPacketProto_PayloadProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PayloadProto.class, Builder.class);
      }

      public static final int PAYLOADBYTES_FIELD_NUMBER = 1;
      private java.util.List<com.google.protobuf.ByteString> payloadBytes_;
      /**
       * <pre>
       * repeated表示可以存在多个（类似数组）
       * </pre>
       *
       * <code>repeated bytes payloadBytes = 1;</code>
       * @return A list containing the payloadBytes.
       */
      @Override
      public java.util.List<com.google.protobuf.ByteString>
          getPayloadBytesList() {
        return payloadBytes_;
      }
      /**
       * <pre>
       * repeated表示可以存在多个（类似数组）
       * </pre>
       *
       * <code>repeated bytes payloadBytes = 1;</code>
       * @return The count of payloadBytes.
       */
      public int getPayloadBytesCount() {
        return payloadBytes_.size();
      }
      /**
       * <pre>
       * repeated表示可以存在多个（类似数组）
       * </pre>
       *
       * <code>repeated bytes payloadBytes = 1;</code>
       * @param index The index of the element to return.
       * @return The payloadBytes at the given index.
       */
      public com.google.protobuf.ByteString getPayloadBytes(int index) {
        return payloadBytes_.get(index);
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (int i = 0; i < payloadBytes_.size(); i++) {
          output.writeBytes(1, payloadBytes_.get(i));
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < payloadBytes_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(payloadBytes_.get(i));
          }
          size += dataSize;
          size += 1 * getPayloadBytesList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof PayloadProto)) {
          return super.equals(obj);
        }
        PayloadProto other = (PayloadProto) obj;

        if (!getPayloadBytesList()
            .equals(other.getPayloadBytesList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getPayloadBytesCount() > 0) {
          hash = (37 * hash) + PAYLOADBYTES_FIELD_NUMBER;
          hash = (53 * hash) + getPayloadBytesList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static PayloadProto parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PayloadProto parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PayloadProto parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PayloadProto parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PayloadProto parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PayloadProto parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PayloadProto parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static PayloadProto parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static PayloadProto parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static PayloadProto parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static PayloadProto parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static PayloadProto parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(PayloadProto prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * 定义payload
       * </pre>
       *
       * Protobuf type {@code DataPacketProto.PayloadProto}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:DataPacketProto.PayloadProto)
          PayloadProtoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return NettyRpcProtobuf.internal_static_DataPacketProto_PayloadProto_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return NettyRpcProtobuf.internal_static_DataPacketProto_PayloadProto_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  PayloadProto.class, Builder.class);
        }

        // Construct using edu.alibaba.mpc4j.common.rpc.impl.netty.protobuf.NettyRpcProtobuf.DataPacketProto.PayloadProto.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          payloadBytes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return NettyRpcProtobuf.internal_static_DataPacketProto_PayloadProto_descriptor;
        }

        @Override
        public PayloadProto getDefaultInstanceForType() {
          return PayloadProto.getDefaultInstance();
        }

        @Override
        public PayloadProto build() {
          PayloadProto result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public PayloadProto buildPartial() {
          PayloadProto result = new PayloadProto(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) != 0)) {
            payloadBytes_ = java.util.Collections.unmodifiableList(payloadBytes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.payloadBytes_ = payloadBytes_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof PayloadProto) {
            return mergeFrom((PayloadProto)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(PayloadProto other) {
          if (other == PayloadProto.getDefaultInstance()) return this;
          if (!other.payloadBytes_.isEmpty()) {
            if (payloadBytes_.isEmpty()) {
              payloadBytes_ = other.payloadBytes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePayloadBytesIsMutable();
              payloadBytes_.addAll(other.payloadBytes_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          PayloadProto parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (PayloadProto) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.util.List<com.google.protobuf.ByteString> payloadBytes_ = java.util.Collections.emptyList();
        private void ensurePayloadBytesIsMutable() {
          if (!((bitField0_ & 0x00000001) != 0)) {
            payloadBytes_ = new java.util.ArrayList<com.google.protobuf.ByteString>(payloadBytes_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <pre>
         * repeated表示可以存在多个（类似数组）
         * </pre>
         *
         * <code>repeated bytes payloadBytes = 1;</code>
         * @return A list containing the payloadBytes.
         */
        public java.util.List<com.google.protobuf.ByteString>
            getPayloadBytesList() {
          return ((bitField0_ & 0x00000001) != 0) ?
                   java.util.Collections.unmodifiableList(payloadBytes_) : payloadBytes_;
        }
        /**
         * <pre>
         * repeated表示可以存在多个（类似数组）
         * </pre>
         *
         * <code>repeated bytes payloadBytes = 1;</code>
         * @return The count of payloadBytes.
         */
        public int getPayloadBytesCount() {
          return payloadBytes_.size();
        }
        /**
         * <pre>
         * repeated表示可以存在多个（类似数组）
         * </pre>
         *
         * <code>repeated bytes payloadBytes = 1;</code>
         * @param index The index of the element to return.
         * @return The payloadBytes at the given index.
         */
        public com.google.protobuf.ByteString getPayloadBytes(int index) {
          return payloadBytes_.get(index);
        }
        /**
         * <pre>
         * repeated表示可以存在多个（类似数组）
         * </pre>
         *
         * <code>repeated bytes payloadBytes = 1;</code>
         * @param index The index to set the value at.
         * @param value The payloadBytes to set.
         * @return This builder for chaining.
         */
        public Builder setPayloadBytes(
            int index, com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadBytesIsMutable();
          payloadBytes_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * repeated表示可以存在多个（类似数组）
         * </pre>
         *
         * <code>repeated bytes payloadBytes = 1;</code>
         * @param value The payloadBytes to add.
         * @return This builder for chaining.
         */
        public Builder addPayloadBytes(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadBytesIsMutable();
          payloadBytes_.add(value);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * repeated表示可以存在多个（类似数组）
         * </pre>
         *
         * <code>repeated bytes payloadBytes = 1;</code>
         * @param values The payloadBytes to add.
         * @return This builder for chaining.
         */
        public Builder addAllPayloadBytes(
            Iterable<? extends com.google.protobuf.ByteString> values) {
          ensurePayloadBytesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, payloadBytes_);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * repeated表示可以存在多个（类似数组）
         * </pre>
         *
         * <code>repeated bytes payloadBytes = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearPayloadBytes() {
          payloadBytes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:DataPacketProto.PayloadProto)
      }

      // @@protoc_insertion_point(class_scope:DataPacketProto.PayloadProto)
      private static final PayloadProto DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new PayloadProto();
      }

      public static PayloadProto getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PayloadProto>
          PARSER = new com.google.protobuf.AbstractParser<PayloadProto>() {
        @Override
        public PayloadProto parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PayloadProto(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<PayloadProto> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<PayloadProto> getParserForType() {
        return PARSER;
      }

      @Override
      public PayloadProto getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int HEADERPROTO_FIELD_NUMBER = 1;
    private HeaderProto headerProto_;
    /**
     * <pre>
     * 协议由两部分组成：head、payload，分别由HeaderProto和PayloadProto定义。
     * </pre>
     *
     * <code>.DataPacketProto.HeaderProto headerProto = 1;</code>
     * @return Whether the headerProto field is set.
     */
    @Override
    public boolean hasHeaderProto() {
      return headerProto_ != null;
    }
    /**
     * <pre>
     * 协议由两部分组成：head、payload，分别由HeaderProto和PayloadProto定义。
     * </pre>
     *
     * <code>.DataPacketProto.HeaderProto headerProto = 1;</code>
     * @return The headerProto.
     */
    @Override
    public HeaderProto getHeaderProto() {
      return headerProto_ == null ? HeaderProto.getDefaultInstance() : headerProto_;
    }
    /**
     * <pre>
     * 协议由两部分组成：head、payload，分别由HeaderProto和PayloadProto定义。
     * </pre>
     *
     * <code>.DataPacketProto.HeaderProto headerProto = 1;</code>
     */
    @Override
    public HeaderProtoOrBuilder getHeaderProtoOrBuilder() {
      return getHeaderProto();
    }

    public static final int PAYLOADPROTO_FIELD_NUMBER = 2;
    private PayloadProto payloadProto_;
    /**
     * <code>.DataPacketProto.PayloadProto payloadProto = 2;</code>
     * @return Whether the payloadProto field is set.
     */
    @Override
    public boolean hasPayloadProto() {
      return payloadProto_ != null;
    }
    /**
     * <code>.DataPacketProto.PayloadProto payloadProto = 2;</code>
     * @return The payloadProto.
     */
    @Override
    public PayloadProto getPayloadProto() {
      return payloadProto_ == null ? PayloadProto.getDefaultInstance() : payloadProto_;
    }
    /**
     * <code>.DataPacketProto.PayloadProto payloadProto = 2;</code>
     */
    @Override
    public PayloadProtoOrBuilder getPayloadProtoOrBuilder() {
      return getPayloadProto();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (headerProto_ != null) {
        output.writeMessage(1, getHeaderProto());
      }
      if (payloadProto_ != null) {
        output.writeMessage(2, getPayloadProto());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (headerProto_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeaderProto());
      }
      if (payloadProto_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPayloadProto());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DataPacketProto)) {
        return super.equals(obj);
      }
      DataPacketProto other = (DataPacketProto) obj;

      if (hasHeaderProto() != other.hasHeaderProto()) return false;
      if (hasHeaderProto()) {
        if (!getHeaderProto()
            .equals(other.getHeaderProto())) return false;
      }
      if (hasPayloadProto() != other.hasPayloadProto()) return false;
      if (hasPayloadProto()) {
        if (!getPayloadProto()
            .equals(other.getPayloadProto())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeaderProto()) {
        hash = (37 * hash) + HEADERPROTO_FIELD_NUMBER;
        hash = (53 * hash) + getHeaderProto().hashCode();
      }
      if (hasPayloadProto()) {
        hash = (37 * hash) + PAYLOADPROTO_FIELD_NUMBER;
        hash = (53 * hash) + getPayloadProto().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DataPacketProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataPacketProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataPacketProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataPacketProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataPacketProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataPacketProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataPacketProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataPacketProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataPacketProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DataPacketProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataPacketProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataPacketProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DataPacketProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataPacketProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataPacketProto)
        DataPacketProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NettyRpcProtobuf.internal_static_DataPacketProto_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NettyRpcProtobuf.internal_static_DataPacketProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DataPacketProto.class, Builder.class);
      }

      // Construct using edu.alibaba.mpc4j.common.rpc.impl.netty.protobuf.NettyRpcProtobuf.DataPacketProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (headerProtoBuilder_ == null) {
          headerProto_ = null;
        } else {
          headerProto_ = null;
          headerProtoBuilder_ = null;
        }
        if (payloadProtoBuilder_ == null) {
          payloadProto_ = null;
        } else {
          payloadProto_ = null;
          payloadProtoBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NettyRpcProtobuf.internal_static_DataPacketProto_descriptor;
      }

      @Override
      public DataPacketProto getDefaultInstanceForType() {
        return DataPacketProto.getDefaultInstance();
      }

      @Override
      public DataPacketProto build() {
        DataPacketProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DataPacketProto buildPartial() {
        DataPacketProto result = new DataPacketProto(this);
        if (headerProtoBuilder_ == null) {
          result.headerProto_ = headerProto_;
        } else {
          result.headerProto_ = headerProtoBuilder_.build();
        }
        if (payloadProtoBuilder_ == null) {
          result.payloadProto_ = payloadProto_;
        } else {
          result.payloadProto_ = payloadProtoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DataPacketProto) {
          return mergeFrom((DataPacketProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DataPacketProto other) {
        if (other == DataPacketProto.getDefaultInstance()) return this;
        if (other.hasHeaderProto()) {
          mergeHeaderProto(other.getHeaderProto());
        }
        if (other.hasPayloadProto()) {
          mergePayloadProto(other.getPayloadProto());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DataPacketProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DataPacketProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private HeaderProto headerProto_;
      private com.google.protobuf.SingleFieldBuilderV3<
          HeaderProto, HeaderProto.Builder, HeaderProtoOrBuilder> headerProtoBuilder_;
      /**
       * <pre>
       * 协议由两部分组成：head、payload，分别由HeaderProto和PayloadProto定义。
       * </pre>
       *
       * <code>.DataPacketProto.HeaderProto headerProto = 1;</code>
       * @return Whether the headerProto field is set.
       */
      public boolean hasHeaderProto() {
        return headerProtoBuilder_ != null || headerProto_ != null;
      }
      /**
       * <pre>
       * 协议由两部分组成：head、payload，分别由HeaderProto和PayloadProto定义。
       * </pre>
       *
       * <code>.DataPacketProto.HeaderProto headerProto = 1;</code>
       * @return The headerProto.
       */
      public HeaderProto getHeaderProto() {
        if (headerProtoBuilder_ == null) {
          return headerProto_ == null ? HeaderProto.getDefaultInstance() : headerProto_;
        } else {
          return headerProtoBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 协议由两部分组成：head、payload，分别由HeaderProto和PayloadProto定义。
       * </pre>
       *
       * <code>.DataPacketProto.HeaderProto headerProto = 1;</code>
       */
      public Builder setHeaderProto(HeaderProto value) {
        if (headerProtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          headerProto_ = value;
          onChanged();
        } else {
          headerProtoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 协议由两部分组成：head、payload，分别由HeaderProto和PayloadProto定义。
       * </pre>
       *
       * <code>.DataPacketProto.HeaderProto headerProto = 1;</code>
       */
      public Builder setHeaderProto(
          HeaderProto.Builder builderForValue) {
        if (headerProtoBuilder_ == null) {
          headerProto_ = builderForValue.build();
          onChanged();
        } else {
          headerProtoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 协议由两部分组成：head、payload，分别由HeaderProto和PayloadProto定义。
       * </pre>
       *
       * <code>.DataPacketProto.HeaderProto headerProto = 1;</code>
       */
      public Builder mergeHeaderProto(HeaderProto value) {
        if (headerProtoBuilder_ == null) {
          if (headerProto_ != null) {
            headerProto_ =
              HeaderProto.newBuilder(headerProto_).mergeFrom(value).buildPartial();
          } else {
            headerProto_ = value;
          }
          onChanged();
        } else {
          headerProtoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 协议由两部分组成：head、payload，分别由HeaderProto和PayloadProto定义。
       * </pre>
       *
       * <code>.DataPacketProto.HeaderProto headerProto = 1;</code>
       */
      public Builder clearHeaderProto() {
        if (headerProtoBuilder_ == null) {
          headerProto_ = null;
          onChanged();
        } else {
          headerProto_ = null;
          headerProtoBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 协议由两部分组成：head、payload，分别由HeaderProto和PayloadProto定义。
       * </pre>
       *
       * <code>.DataPacketProto.HeaderProto headerProto = 1;</code>
       */
      public HeaderProto.Builder getHeaderProtoBuilder() {
        
        onChanged();
        return getHeaderProtoFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 协议由两部分组成：head、payload，分别由HeaderProto和PayloadProto定义。
       * </pre>
       *
       * <code>.DataPacketProto.HeaderProto headerProto = 1;</code>
       */
      public HeaderProtoOrBuilder getHeaderProtoOrBuilder() {
        if (headerProtoBuilder_ != null) {
          return headerProtoBuilder_.getMessageOrBuilder();
        } else {
          return headerProto_ == null ?
              HeaderProto.getDefaultInstance() : headerProto_;
        }
      }
      /**
       * <pre>
       * 协议由两部分组成：head、payload，分别由HeaderProto和PayloadProto定义。
       * </pre>
       *
       * <code>.DataPacketProto.HeaderProto headerProto = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          HeaderProto, HeaderProto.Builder, HeaderProtoOrBuilder>
          getHeaderProtoFieldBuilder() {
        if (headerProtoBuilder_ == null) {
          headerProtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              HeaderProto, HeaderProto.Builder, HeaderProtoOrBuilder>(
                  getHeaderProto(),
                  getParentForChildren(),
                  isClean());
          headerProto_ = null;
        }
        return headerProtoBuilder_;
      }

      private PayloadProto payloadProto_;
      private com.google.protobuf.SingleFieldBuilderV3<
          PayloadProto, PayloadProto.Builder, PayloadProtoOrBuilder> payloadProtoBuilder_;
      /**
       * <code>.DataPacketProto.PayloadProto payloadProto = 2;</code>
       * @return Whether the payloadProto field is set.
       */
      public boolean hasPayloadProto() {
        return payloadProtoBuilder_ != null || payloadProto_ != null;
      }
      /**
       * <code>.DataPacketProto.PayloadProto payloadProto = 2;</code>
       * @return The payloadProto.
       */
      public PayloadProto getPayloadProto() {
        if (payloadProtoBuilder_ == null) {
          return payloadProto_ == null ? PayloadProto.getDefaultInstance() : payloadProto_;
        } else {
          return payloadProtoBuilder_.getMessage();
        }
      }
      /**
       * <code>.DataPacketProto.PayloadProto payloadProto = 2;</code>
       */
      public Builder setPayloadProto(PayloadProto value) {
        if (payloadProtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payloadProto_ = value;
          onChanged();
        } else {
          payloadProtoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.DataPacketProto.PayloadProto payloadProto = 2;</code>
       */
      public Builder setPayloadProto(
          PayloadProto.Builder builderForValue) {
        if (payloadProtoBuilder_ == null) {
          payloadProto_ = builderForValue.build();
          onChanged();
        } else {
          payloadProtoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.DataPacketProto.PayloadProto payloadProto = 2;</code>
       */
      public Builder mergePayloadProto(PayloadProto value) {
        if (payloadProtoBuilder_ == null) {
          if (payloadProto_ != null) {
            payloadProto_ =
              PayloadProto.newBuilder(payloadProto_).mergeFrom(value).buildPartial();
          } else {
            payloadProto_ = value;
          }
          onChanged();
        } else {
          payloadProtoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.DataPacketProto.PayloadProto payloadProto = 2;</code>
       */
      public Builder clearPayloadProto() {
        if (payloadProtoBuilder_ == null) {
          payloadProto_ = null;
          onChanged();
        } else {
          payloadProto_ = null;
          payloadProtoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.DataPacketProto.PayloadProto payloadProto = 2;</code>
       */
      public PayloadProto.Builder getPayloadProtoBuilder() {
        
        onChanged();
        return getPayloadProtoFieldBuilder().getBuilder();
      }
      /**
       * <code>.DataPacketProto.PayloadProto payloadProto = 2;</code>
       */
      public PayloadProtoOrBuilder getPayloadProtoOrBuilder() {
        if (payloadProtoBuilder_ != null) {
          return payloadProtoBuilder_.getMessageOrBuilder();
        } else {
          return payloadProto_ == null ?
              PayloadProto.getDefaultInstance() : payloadProto_;
        }
      }
      /**
       * <code>.DataPacketProto.PayloadProto payloadProto = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          PayloadProto, PayloadProto.Builder, PayloadProtoOrBuilder>
          getPayloadProtoFieldBuilder() {
        if (payloadProtoBuilder_ == null) {
          payloadProtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              PayloadProto, PayloadProto.Builder, PayloadProtoOrBuilder>(
                  getPayloadProto(),
                  getParentForChildren(),
                  isClean());
          payloadProto_ = null;
        }
        return payloadProtoBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DataPacketProto)
    }

    // @@protoc_insertion_point(class_scope:DataPacketProto)
    private static final DataPacketProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DataPacketProto();
    }

    public static DataPacketProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataPacketProto>
        PARSER = new com.google.protobuf.AbstractParser<DataPacketProto>() {
      @Override
      public DataPacketProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataPacketProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataPacketProto> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DataPacketProto> getParserForType() {
      return PARSER;
    }

    @Override
    public DataPacketProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataPacketProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataPacketProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataPacketProto_HeaderProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataPacketProto_HeaderProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataPacketProto_PayloadProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataPacketProto_PayloadProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016NettyRpc.proto\"\226\002\n\017DataPacketProto\0221\n\013" +
      "headerProto\030\001 \001(\0132\034.DataPacketProto.Head" +
      "erProto\0223\n\014payloadProto\030\002 \001(\0132\035.DataPack" +
      "etProto.PayloadProto\032u\n\013HeaderProto\022\016\n\006t" +
      "askId\030\001 \001(\003\022\r\n\005ptoId\030\002 \001(\005\022\016\n\006stepId\030\003 \001" +
      "(\005\022\021\n\textraInfo\030\004 \001(\003\022\020\n\010senderId\030\005 \001(\005\022" +
      "\022\n\nreceiverId\030\006 \001(\005\032$\n\014PayloadProto\022\024\n\014p" +
      "ayloadBytes\030\001 \003(\014BG\n3edu.alibaba.mpc4j." +
      "common.rpc.impl.netty.protobufB\020NettyR" +
      "pcProtobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DataPacketProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DataPacketProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataPacketProto_descriptor,
        new String[] { "HeaderProto", "PayloadProto", });
    internal_static_DataPacketProto_HeaderProto_descriptor =
      internal_static_DataPacketProto_descriptor.getNestedTypes().get(0);
    internal_static_DataPacketProto_HeaderProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataPacketProto_HeaderProto_descriptor,
        new String[] { "TaskId", "PtoId", "StepId", "ExtraInfo", "SenderId", "ReceiverId", });
    internal_static_DataPacketProto_PayloadProto_descriptor =
      internal_static_DataPacketProto_descriptor.getNestedTypes().get(1);
    internal_static_DataPacketProto_PayloadProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataPacketProto_PayloadProto_descriptor,
        new String[] { "PayloadBytes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
