/*
 * @Description: 
 * @Author: Qixian Zhou
 * @Date: 2023-04-05 16:05:51
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_common_tool_crypto_ecc_fourq_FourqByteFullEcc */

#ifndef _Included_edu_alibaba_mpc4j_common_tool_crypto_ecc_fourq_FourqByteFullEcc
#define _Included_edu_alibaba_mpc4j_common_tool_crypto_ecc_fourq_FourqByteFullEcc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_common_tool_crypto_ecc_fourq_FourqByteFullEcc
 * Method:    nativeMul
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_crypto_ecc_fourq_FourqByteFullEcc_nativeMul
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_crypto_ecc_fourq_FourqByteFullEcc
 * Method:    nativeBaseMul
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_crypto_ecc_fourq_FourqByteFullEcc_nativeBaseMul
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_crypto_ecc_fourq_FourqByteFullEcc
 * Method:    nativeIsValidPoint
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_alibaba_mpc4j_common_tool_crypto_ecc_fourq_FourqByteFullEcc_nativeIsValidPoint
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_crypto_ecc_fourq_FourqByteFullEcc
 * Method:    nativeNeg
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_crypto_ecc_fourq_FourqByteFullEcc_nativeNeg
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_crypto_ecc_fourq_FourqByteFullEcc
 * Method:    nativeAdd
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_crypto_ecc_fourq_FourqByteFullEcc_nativeAdd
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_crypto_ecc_fourq_FourqByteFullEcc
 * Method:    nativeHashToCurve
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_crypto_ecc_fourq_FourqByteFullEcc_nativeHashToCurve
  (JNIEnv *, jobject, jbyteArray);


#ifdef __cplusplus
}
#endif
#endif
