/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer */

#ifndef _Included_edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer
#define _Included_edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer
 * Method:    computeEncryptedPowers
 * Signature: ([B[BLjava/util/List;[[I[II)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer_computeEncryptedPowers
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject, jobjectArray, jintArray, jint);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer
 * Method:    computeMatches
 * Signature: ([B[B[[JLjava/util/List;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer_computeMatches
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobjectArray, jobject, jint);

/*
 * Class:     edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer
 * Method:    computeMatchesNaiveMethod
 * Signature: ([B[B[[JLjava/util/List;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_s2pc_pso_upsi_cmg21_Cmg21UpsiNativeServer_computeMatchesNaiveMethod
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
