/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_alibaba_mpc4j_common_tool_polynomial_gf2e_NtlNativeGf2ePoly */

#ifndef _Included_edu_alibaba_mpc4j_common_tool_polynomial_gf2e_NtlNativeGf2ePoly
#define _Included_edu_alibaba_mpc4j_common_tool_polynomial_gf2e_NtlNativeGf2ePoly
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_alibaba_mpc4j_common_tool_polynomial_gf2e_NtlNativeGf2ePoly
 * Method:    interpolate
 * Signature: ([BII[[B[[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_edu_alibaba_mpc4j_common_tool_polynomial_gf2e_NtlNativeGf2ePoly_interpolate
  (JNIEnv *, jclass, jbyteArray, jint, jint, jobjectArray, jobjectArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_polynomial_gf2e_NtlNativeGf2ePoly
 * Method:    rootInterpolate
 * Signature: ([BII[[B[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_edu_alibaba_mpc4j_common_tool_polynomial_gf2e_NtlNativeGf2ePoly_rootInterpolate
  (JNIEnv *, jclass, jbyteArray, jint, jint, jobjectArray, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_polynomial_gf2e_NtlNativeGf2ePoly
 * Method:    singleEvaluate
 * Signature: ([BI[[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_alibaba_mpc4j_common_tool_polynomial_gf2e_NtlNativeGf2ePoly_singleEvaluate
  (JNIEnv *, jclass, jbyteArray, jint, jobjectArray, jbyteArray);

/*
 * Class:     edu_alibaba_mpc4j_common_tool_polynomial_gf2e_NtlNativeGf2ePoly
 * Method:    zp_tree_main_evaluate
 * Signature: ([BI[[B[[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_edu_alibaba_mpc4j_common_tool_polynomial_gf2e_NtlNativeGf2ePoly_evaluate
  (JNIEnv *, jclass, jbyteArray, jint, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
